#!/usr/bin/env bash

if { xset q | grep "DPMS is Disabled"; }  > /dev/null; then
    xset +dpms
    echo "DPMS is Enabled"
exit 0
fi

if { xset q | grep "DPMS is Enabled"; } > /dev/null; then
    xset -dpms
    echo "DPMS is Disabled"
exit 0
fi

